moments/blueprints/admin.py
from flask import Blueprint, current_app, flash, render_template, request, abort, redirect, url_for
from flask_login import login_required
from sqlalchemy import func, select

from moments.core.extensions import db
from moments.decorators import admin_required, permission_required
from moments.forms.admin import EditProfileAdminForm
from moments.models import Comment, Photo, Role, Tag, User
from moments.utils import redirect_back

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/')
@login_required
@permission_required('MODERATE')
def index():
    user_count = db.session.scalar(select(func.count(User.id)))
    locked_user_count = db.session.scalar(select(func.count(User.id)).filter_by(locked=True))
    blocked_user_count = db.session.scalar(select(func.count(User.id)).filter_by(active=False))
    photo_count = db.session.scalar(select(func.count(Photo.id)))
    reported_photos_count = db.session.scalar(select(func.count(Photo.id)).filter(Photo.flag > 0))
    tag_count = db.session.scalar(select(func.count(Tag.id)))
    comment_count = db.session.scalar(select(func.count(Comment.id)))
    reported_comments_count = db.session.scalar(select(func.count(Comment.id)).filter(Comment.flag > 0))
    return render_template(
        'admin/index.html',
        user_count=user_count,
        photo_count=photo_count,
        tag_count=tag_count,
        comment_count=comment_count,
        locked_user_count=locked_user_count,
        blocked_user_count=blocked_user_count,
        reported_comments_count=reported_comments_count,
        reported_photos_count=reported_photos_count,
    )


@admin_bp.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
    user = db.session.get(User, user_id) or abort(404)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.name = form.name.data
        role = db.session.get(Role, form.role.data)
        if role.name == 'Locked':
            user.lock()
        user.role = role
        user.bio = form.bio.data
        user.website = form.website.data
        user.confirmed = form.confirmed.data
        user.active = form.active.data
        user.location = form.location.data
        user.username = form.username.data
        user.email = form.email.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect_back()
    if request.method == 'GET':
        form.name.data = user.name
        form.role.data = user.role_id
        form.bio.data = user.bio
        form.website.data = user.website
        form.location.data = user.location
        form.username.data = user.username
        form.email.data = user.email
        form.confirmed.data = user.confirmed
        form.active.data = user.active
    return render_template('admin/edit_profile.html', form=form, user=user)


@admin_bp.route('/block/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def block_user(user_id):
    user = db.session.get(User, user_id) or abort(404)
    if user.role.name in ['Administrator', 'Moderator']:
        flash('Permission denied.', 'warning')
    else:
        user.block()
        flash('Account blocked.', 'info')
    return redirect_back()


@admin_bp.route('/unblock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unblock_user(user_id):
    user = db.session.get(User, user_id) or abort(404)
    user.unblock()
    flash('Block canceled.', 'info')
    return redirect_back()


@admin_bp.route('/lock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def lock_user(user_id):
    user = db.session.get(User, user_id) or abort(404)
    if user.role.name in ['Administrator', 'Moderator']:
        flash('Permission denied.', 'warning')
    else:
        user.lock()
        flash('Account locked.', 'info')
    return redirect_back()


@admin_bp.route('/unlock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unlock_user(user_id):
    user = db.session.get(User, user_id) or abort(404)
    user.unlock()
    flash('Lock canceled.', 'info')
    return redirect_back()


@admin_bp.route('/delete/tag/<int:tag_id>', methods=['GET', 'POST'])
@login_required
@permission_required('MODERATE')
def delete_tag(tag_id):
    tag = db.session.get(Tag, tag_id) or abort(404)
    db.session.delete(tag)
    db.session.commit()
    flash('Tag deleted.', 'info')
    return redirect_back()


@admin_bp.route('/manage/user')
@login_required
@permission_required('MODERATE')
def manage_user():
    filter_rule = request.args.get('filter', 'all')  # 'all', 'locked', 'blocked', 'administrator', 'moderator'
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOMENTS_MANAGE_USER_PER_PAGE']
    administrator = db.session.scalar(select(Role).filter_by(name='Administrator'))
    moderator = db.session.scalar(select(Role).filter_by(name='Moderator'))

    if filter_rule == 'locked':
        filtered_users = select(User).filter_by(locked=True)
    elif filter_rule == 'blocked':
        filtered_users = select(User).filter_by(active=False)
    elif filter_rule == 'administrator':
        filtered_users = select(User).filter_by(role=administrator)
    elif filter_rule == 'moderator':
        filtered_users = select(User).filter_by(role=moderator)
    else:
        filtered_users = select(User)

    pagination = db.paginate(filtered_users.order_by(User.member_since.desc()), page=page, per_page=per_page)
    users = pagination.items
    return render_template('admin/manage_user.html', pagination=pagination, users=users)


@admin_bp.route('/manage/photo', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/photo/<order>')
@login_required
@permission_required('MODERATE')
def manage_photo(order):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOMENTS_MANAGE_PHOTO_PER_PAGE']
    order_rule = 'flag'
    if order == 'by_time':
        pagination = db.paginate(select(Photo).order_by(Photo.created_at.desc()), page=page, per_page=per_page, error_out=False)
        order_rule = 'time'
    else:
        pagination = db.paginate(select(Photo).order_by(Photo.flag.desc()), page=page, per_page=per_page, error_out=False)
    if page > pagination.pages:
        return redirect(url_for('.manage_photo', page=pagination.pages, order_rule=order_rule))
    photos = pagination.items
    return render_template('admin/manage_photo.html', pagination=pagination, photos=photos, order_rule=order_rule)


@admin_bp.route('/manage/tag')
@login_required
@permission_required('MODERATE')
def manage_tag():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOMENTS_MANAGE_TAG_PER_PAGE']
    pagination = db.paginate(select(Tag).order_by(Tag.id.desc()), page=page, per_page=per_page)
    tags = pagination.items
    return render_template('admin/manage_tag.html', pagination=pagination, tags=tags)


@admin_bp.route('/manage/comment', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/comment/<order>')
@login_required
@permission_required('MODERATE')
def manage_comment(order):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOMENTS_MANAGE_COMMENT_PER_PAGE']
    order_rule = 'flag'
    if order == 'by_time':
        pagination = db.paginate(select(Comment).order_by(Comment.created_at.desc()), page=page, per_page=per_page, error_out=False)
        order_rule = 'time'
    else:
        pagination = db.paginate(select(Comment).order_by(Comment.flag.desc()), page=page, per_page=per_page, error_out=False)
    if page > pagination.pages:
        return redirect(url_for('.manage_comment', page=pagination.pages, order_rule=order_rule))
    comments = pagination.items
    return render_template('admin/manage_comment.html', pagination=pagination, comments=comments, order_rule=order_rule)


@admin_bp.route('/delete/photo/<int:photo_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def delete_photo(photo_id):
    photo = db.session.get(Photo, photo_id) or abort(404)
    db.session.delete(photo)
    db.session.commit()
    flash('Photo deleted.', 'info')
    return redirect_back()


@admin_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def delete_comment(comment_id):
    comment = db.session.get(Comment, comment_id) or abort(404)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'info')
    return redirect_back()

moments/blueprints/ajax.py
from flask import Blueprint, render_template, abort
from flask_login import current_user
from sqlalchemy import func, select

from moments.core.extensions import db
from moments.models import Notification, Photo, User
from moments.notifications import push_collect_notification, push_follow_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return {'message': 'Login required.'}, 403

    stmt = current_user.notifications.select().filter_by(is_read=False).with_only_columns(func.count())
    count = db.session.scalar(stmt)
    return {'count': count}


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = db.session.get(User, user_id) or abort(404)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = db.session.get(User, user_id) or abort(404)
    return {'count': user.followers_count}


@ajax_bp.route('/collectors-count/<int:photo_id>')
def collectors_count(photo_id):
    photo = db.session.get(Photo, photo_id) or abort(404)
    return {'count': photo.collectors_count}


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    if not current_user.is_authenticated:
        return {'message': 'Login required.'}, 403
    if not current_user.confirmed:
        return {'message': 'Confirm account required.'}, 400
    if not current_user.can('COLLECT'):
        return {'message': 'No permission.'}, 403

    photo = db.session.get(Photo, photo_id) or abort(404)
    if current_user.is_collecting(photo):
        return {'message': 'Already collected.'}, 400

    current_user.collect(photo)
    if current_user != photo.author:
        push_collect_notification(user=current_user, photo_id=photo_id, receiver=photo.author)
    return {'message': 'Photo collected.'}


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    if not current_user.is_authenticated:
        return {'message': 'Login required.'}, 403

    photo = db.session.get(Photo, photo_id) or abort(404)
    if not current_user.is_collecting(photo):
        return {'message': 'Not collect yet.'}, 400

    current_user.uncollect(photo)
    return {'message': 'Collect canceled.'}


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return {'message': 'Login required.'}, 403
    if not current_user.confirmed:
        return {'message': 'Confirm account required.'}, 400
    if not current_user.can('FOLLOW'):
        return {'message': 'No permission.'}, 403

    user = db.session.scalar(select(User).filter_by(username=username)) or abort(404)
    if current_user.is_following(user):
        return {'message': 'Already followed.'}, 400

    current_user.follow(user)
    push_follow_notification(follower=current_user, receiver=user)
    return {'message': 'User followed.'}


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return {'message': 'Login required.'}, 403

    user = db.session.scalar(select(User).filter_by(username=username)) or abort(404)
    if not current_user.is_following(user):
        return {'message': 'Not following yet.'}, 400

    current_user.unfollow(user)
    return {'message': 'Follow canceled.'}

moments/blueprints/auth.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import confirm_login, current_user, login_fresh, login_required, login_user, logout_user
from sqlalchemy import select

from moments.core.extensions import db
from moments.emails import send_confirmation_email, send_reset_password_email
from moments.forms.auth import ForgetPasswordForm, LoginForm, RegisterForm, ResetPasswordForm
from moments.models import User
from moments.settings import Operations
from moments.utils import generate_token, parse_token, redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        stmt = select(User).filter_by(email=form.email.data.lower())
        user = db.session.scalar(stmt)
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('Login success.', 'info')
                return redirect_back()
            else:
                flash('Your account is blocked.', 'warning')
                return redirect(url_for('main.index'))
        flash('Invalid email or password.', 'warning')
        return redirect(url_for('.login'))
    return render_template('auth/login.html', form=form)


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username, password=password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        token = generate_token(user=user, operation=Operations.CONFIRM)
        send_confirmation_email(user=user, token=token)
        flash('Confirmation email sent, please check your inbox.', 'info')
        return redirect(url_for('main.index'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    if parse_token(user=current_user, token=token, operation=Operations.CONFIRM):
        current_user.confirmed = True
        db.session.commit()
        flash('Account confirmed.', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('Invalid or expired token.', 'danger')
        return redirect(url_for('.resend_confirmation_email'))


@auth_bp.route('/resend-confirmation-email')
@login_required
def resend_confirmation_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirmation_email(user=current_user, token=token)
    flash('New email sent, please check your inbox.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        stmt = select(User).filter_by(email=form.email.data.lower())
        user = db.session.scalar(stmt)
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('Password reset email sent, please check your inbox.', 'info')
            return redirect(url_for('.login'))
        flash('Invalid email.', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        stmt = select(User).filter_by(email=form.email.data.lower())
        user = db.session.scalar(stmt)
        if user is None:
            return redirect(url_for('main.index'))
        if parse_token(user=user, token=token, operation=Operations.RESET_PASSWORD):
            user.password = form.password.data
            db.session.commit()
            flash('Password updated.', 'success')
            return redirect(url_for('.login'))
        else:
            flash('Invalid or expired link.', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

moments/templates/base.html
{% from 'bootstrap5/nav.html' import render_nav_item %}
{% from 'bootstrap5/utils.html' import render_icon, render_messages %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block head %}
  <title>{% block title %}{% endblock %} - Moments</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  {% block styles %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  {% endblock styles %}
  {% endblock head %}
</head>

<body>
  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">
        <img src="{{ url_for('static', filename='favicon.ico') }}" alt="Moments">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
        aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav me-auto">
          {{ render_nav_item('main.index', 'Home') }}
          {{ render_nav_item('main.explore', 'Explore') }}
          <form class="d-flex" role="search" action="{{ url_for('main.search') }}">
            <input class="form-control me-2" name="q" type="search" placeholder="Photo, tag or user" aria-label="Search" required>
            <button class="btn btn-light my-2 my-sm-0" type="submit">
              {{ render_icon('search') }}
            </button>
          </form>
        </div>
        <div class="navbar-nav ms-auto">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" href="{{ url_for('main.show_notifications', filter='unread') }}">
            <span class="position-relative">
              {{ render_icon('bell-fill') }}
              <span
                id="notification-badge"
                class="{% if notification_count == 0 %}hide{% endif %} position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                data-href="{{ url_for('ajax.notifications_count') }}"
              >
                {{ notification_count }}
                <span class="visually-hidden">unread messages</span>
              </span>
            </span>
          </a>
          <a class="nav-item nav-link" href="{{ url_for('main.upload') }}" title="Upload">
            {{ render_icon('plus-circle-fill') }}
          </a>
          <div class="dropdown nav-item">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
              <img class="avatar-xs" src="{{ url_for('main.get_avatar', filename=current_user.avatar_s) }}">
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" role="menu">
              <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
              <li>
                <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}">
                {{ render_icon('person-fill') }} My Home
                </a>
              </li>
              <div class="dropdown-divider"></div>
              <li>
                <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                {{ render_icon('gear-fill') }} Settings
                </a>
              </li>
              {% if current_user.can('MODERATE') %}
              <li>
                <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                {{ render_icon('speedometer') }} Dashboard
                </a>
              </li>
              {% endif %}
              <li>
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                {{ render_icon('power') }} Logout
                </a>
              </li>
            </div>
          </div>
          {% else %}
          <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">Login</a>&nbsp;&nbsp;
          <a class="btn btn-primary" href="{{ url_for('auth.register') }}">Join Moments</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  {% endblock %}

  <main>
    <div class="container">
      {{ render_messages(dismissible=True, dismiss_animate=True) }}
      {% block content %}{% endblock %}
      {% block footer %}
      <footer>
        <p class="float-start">
          <small>&copy; 2025 Moments -
            <a href="https://greyli.com" title="Written by Grey Li">Grey Li</a> -
            <a href="https://github.com/greyli/moments" title="Fork me on GitHub">GitHub</a> -
            <a href="https://helloflask.com" title="A HelloFlask project">HelloFlask</a>
          </small>
        </p>
        <p class="float-end">
          <small>Capture and share every wonderful moment.</small>
        </p>
      </footer>
      {% endblock %}
    </div>
  </main>
  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="mainToast" class="toast align-items-center border-0 text-bg-secondary" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body text-white"></div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  </div>

  {% block scripts %}
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/dayjs/dayjs.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/dayjs/plugin/relativeTime.js') }}"></script>
  <script src="{{ url_for('static', filename='js/dayjs/plugin/utc.js') }}"></script>
  <script src="{{ url_for('static', filename='js/dayjs/plugin/localizedFormat.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  <script type="text/javascript">
    const csrfToken = "{{ csrf_token() }}";
    const isAuthenticated = {{ current_user.is_authenticated|tojson }};
  </script>
  {% endblock %}
</body>

</html>

moments/templates/macros.html
{% from 'bootstrap5/utils.html' import render_icon %}

{% macro photo_card(photo) %}
<div class="photo-card card">
  <a class="card-thumbnail" href="{{ url_for('main.show_photo', photo_id=photo.id) }}">
    <img class="card-img-top portrait" src="{{ url_for('main.get_image', filename=photo.filename_s) }}">
  </a>
  <div class="card-body">
    {{ render_icon('suit-heart-fill') }} {{ photo.collectors_count }}
    {{ render_icon('chat-left-fill') }} {{ photo.comments_count }}
  </div>
</div>
{% endmacro %}

{% macro user_card(user) %}
<div class="user-card text-center">
  <a href="{{ url_for('user.index', username=user.username) }}">
    <img class="rounded avatar-m" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
  </a>
  <h6>
    <a class="text-decoration-none" href="{{ url_for('user.index', username=user.username) }}">{{ user.name }}</a>
  </h6>
  {{ follow_area(user) }}
</div>
{% endmacro %}

{% macro follow_area(user) %}
{% if current_user.is_authenticated %}
  {% if user != current_user %}
    {% if current_user.is_following(user) %}
    <form class="inline" method="post"
      action="{{ url_for('user.unfollow', username=user.username, next=request.full_path) }}">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <button type="submit" class="btn btn-secondary btn-sm">Unfollow</button>
      {% if current_user.is_followed_by(user) %}
      <p class="badge text-bg-light rounded-pill">Follow each other</p>
      {% endif %}
    </form>
    {% else %}
    <form class="inline" method="post"
      action="{{ url_for('user.follow', username=user.username, next=request.full_path) }}">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <button type="submit" class="btn btn-primary btn-sm">Follow</button>
      {% if current_user.is_followed_by(user) %}
      <p class="badge text-bg-light rounded-pill">Follows you</p>
      {% endif %}
    </form>
    {% endif %}
  {% endif %}
{% else %}
<form class="inline" method="post" action="{{ url_for('user.follow', username=user.username) }}">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <button type="submit" class="btn btn-primary btn-sm">Follow</button>
</form>
{% endif %}
{% endmacro %}